openapi: 3.0.3
info:
  title: One Message
  description: One Message用API
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: ユーザー関係
  - name: auth
    description: 認証関係
  - name: twitter
    description: twitter関係
  - name: dm
    description: dm関係
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      description: ログイン
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/loginRequest.yaml"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /register:
    post:
      tags:
        - user
      summary: ユーザー情報登録
      description: ユーザー情報を新規登録
      operationId: createMe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/createMeRequest.yaml"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /me:
    get:
      tags:
        - user
      summary: ユーザー情報取得
      description: ユーザー情報を習得
      operationId: getMe
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getMeResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /dm:
    post:
      tags:
        - dm
      summary: dm送信
      description: dmを送信
      operationId: postDm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/postDmRequest.yaml"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /twitter/account:
    get:
      tags:
        - twitter
      summary: ユーザーのTwitter情報を取得
      description: ユーザーのTwitter情報を取得
      operationId: getTwitterAccount
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getTwitterAccountResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /twitter/account/followers:
    get:
      tags:
        - twitter
      summary: Twitterアカウントのフォロワー情報の取得
      description: ユーザーのTwitterアカウントのフォロワー情報の取得
      operationId: getTwitterAccountFollowers
      security:
        - Authorization: []
      parameters:
        - name: offset
          in: query
          allowEmptyValue: true
          description: |
            フォロワーの取得開始位置
            指定されない場合は、0から開始される
          schema:
            type: integer
        - name: limit
          in: query
          allowEmptyValue: true
          description: |
            フォロワーの取得数
            指定されない場合は、最大量まで取得される
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getTwitterAccountFollowersResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /twitter/auth:
    post:
      tags:
        - twitter
      summary: アクセストークンの登録
      description: Firebaseから取得した、アクセストークンを登録する
      operationId: createTwitterAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/createTwitterAccessTokenRequest.yaml"
      security:
        - Authorization: []
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    delete:
      tags:
        - twitter
      summary: twitterアクセストークンを削除
      description: アクセストークンを削除
      operationId: deleteTwitterAccessToken
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
