openapi: 3.0.3
info:
  title: One Message
  description: One Message用API
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: ユーザー関係
  - name: auth
    description: 認証関係
  - name: twitter
    description: twitter関係
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      description: ログイン
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/loginRequest.yaml"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /register:
    post:
      tags:
        - user
      summary: ユーザー情報登録
      description: ユーザー情報を新規登録
      operationId: createMe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/createMeRequest.yaml"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /me:
    get:
      tags:
        - user
      summary: ユーザー情報取得
      description: ユーザー情報を習得
      operationId: getMe
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getMeResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /user/{userId}/twitter:
    get:
      tags:
        - twitter
      summary: ユーザー情報のTwitter情報を取得
      description: ユーザー情報のTwitter情報を取得
      operationId: getTwitterAccount
      security:
        - Authorization: []
      parameters:
        - name: userId
          description: ユーザーID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/getTwitterAccountResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /twitter/auth:
    post:
      tags:
        - twitter
      summary: アクセストークンの登録
      description: Firebaseから取得した、アクセストークンを登録する
      operationId: createTwitterAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/createTwitterAccessTokenRequest.yaml"
      security:
        - Authorization: []
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    delete:
      tags:
        - twitter
      summary: twitterアクセストークンを削除
      description: アクセストークンを削除
      operationId: deleteTwitterAccessToken
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
