openapi: 3.0.3
info:
  title: One Message
  description: One Message用API
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: ユーザー関係
  - name: auth
    description: 認証関係
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      description: ログイン
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "./schemas/loginRequest.yaml"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /register:
    post:
      tags:
        - user
      summary: ユーザー情報登録
      description: ユーザー情報を新規登録
      operationId: createMe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "./schemas/createMeRequest.yaml"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /me:
    post:
      tags:
        - user
      summary: ユーザー情報取得
      description: ユーザー情報を習得
      operationId: getMe
      security:
        - Authorization: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "./schemas/getMeResponse.yaml"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
